#!/usr/bin/env bash

# Write gateway IP for reference
echo "$route_vpn_gateway" > /opt/piavpn-manual/route_info

# Back up resolv.conf and create new one with PIA DNS
cat /etc/resolv.conf > /opt/piavpn-manual/resolv_conf_backup
echo "# Generated by /connect_to_openvpn_with_token.sh
nameserver 10.0.0.241" > /etc/resolv.conf
