#!/bin/bash

sudo VPN_PROTOCOL=$VPN_PROTOCOL 
DISABLE_IPV6=$DISABLE_IPV6 
DIP_TOKEN=$DIP_TOKEN 
AUTOCONNECT=$AUTOCONNECT 
PIA_PF=$PIA_PF 
PIA_DNS=$PIA_DNS 
PIA_USER=$PIA_USER 
PIA_PASS=$PIA_PASS 
PIA_CONNECT=$PIA_CONNECT 
PIA_CONF_PATH=$PIA_CONF_PATH 
MAX_LATENCY=$MAX_LATENCY 
PREFERRED_REGION=$PREFERRED_REGION 
./run_setup.sh

# Keep the container running
tail -f /dev/null